I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 17, in script
    "Lo que le siguió fue un grito"
IOError: Couldn't find file 'Music/Sound/Espadas.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 17, in script
    "Lo que le siguió fue un grito"
  File "/Applications/renpy-7.2.1-sdk/renpy/ast.py", line 690, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Applications/renpy-7.2.1-sdk/renpy/exports.py", line 1322, in say
    who(what, *args, **kwargs)
  File "/Applications/renpy-7.2.1-sdk/renpy/character.py", line 1127, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "/Applications/renpy-7.2.1-sdk/renpy/character.py", line 842, in do_display
    **display_args)
  File "/Applications/renpy-7.2.1-sdk/renpy/character.py", line 591, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "/Applications/renpy-7.2.1-sdk/renpy/ui.py", line 289, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Applications/renpy-7.2.1-sdk/renpy/display/core.py", line 2690, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "/Applications/renpy-7.2.1-sdk/renpy/display/core.py", line 3360, in interact_core
    renpy.audio.audio.periodic()
  File "/Applications/renpy-7.2.1-sdk/renpy/audio/audio.py", line 1019, in periodic
    six.reraise(exc[0], exc[1], exc[2])
  File "/Applications/renpy-7.2.1-sdk/renpy/audio/audio.py", line 997, in periodic_thread_main
    periodic_pass()
  File "/Applications/renpy-7.2.1-sdk/renpy/audio/audio.py", line 938, in periodic_pass
    c.periodic()
  File "/Applications/renpy-7.2.1-sdk/renpy/audio/audio.py", line 420, in periodic
    topf = load(self.file_prefix + filename + self.file_suffix)
  File "/Applications/renpy-7.2.1-sdk/renpy/audio/audio.py", line 72, in load
    rv = renpy.loader.load(fn)
  File "/Applications/renpy-7.2.1-sdk/renpy/loader.py", line 576, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'Music/Sound/Espadas.mp3'.

Darwin-18.6.0-x86_64-i386-64bit
Ren'Py 7.2.1.457
TlamiEsp 1.0
Tue Jun  4 14:54:03 2019
